name: Run tests

on:
  push:
    branches:
      - dev
      - debug

  workflow_dispatch: # allow to run this workflow manually

jobs:

  validate_on_os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Check out project to runner
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          check-latest: true

      # xvfb on Ubuntu is necessary to avoid java.awt.HeadlessException
      - name: Install Xvfb (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install xvfb

      - name: Execute gradle assemble (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          chmod +x gradlew
          ./gradlew assemble --no-daemon
        shell: bash

      - name: Execute gradle assemble (not Windows)
        if: matrix.os != 'windows-latest'
        run: |
          chmod +x gradlew
          ./gradlew assemble
        shell: bash

      - name: Execute gradle test (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run ./gradlew test
        shell: bash

      - name: Execute gradle test (not Ubuntu)
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew test
        shell: bash

      - name: Execute gradle lint (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew lint

      - name: Stop gradle (Windows)
        if: matrix.os == 'windows-latest'
        run: ./gradlew --stop
        shell: bash