name: Run tests

on:
  push:
    branches:
      - dev

  workflow_dispatch: # allow to run this workflow manually

jobs:

  assemble:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Check out project to runner
        uses: actions/checkout@v3

      - name: Set up JDK 15
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          check-latest: true

      - name: Execute gradle assemble
        run: |
          chmod +x gradlew
          ./gradlew assemble
        shell: bash

  test:
    needs: assemble
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Execute gradle test
        run: ./gradlew test
        shell: bash

  lint:
    needs: assemble
    runs-on: ubuntu-latest

    steps:
      - name: Execute gradle lint
        run: ./gradlew lint
        shell: bash