name: Run tests

on:
  push:
    branches:
      - dev

  workflow_dispatch: # allow to run this workflow manually

jobs:

  validate_on_os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Check out project to runner
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
          check-latest: true

      - name: Execute gradle assemble
        run: |
          chmod +x gradlew
          ./gradlew assemble
        shell: bash

      - name: Execute gradle test
        run: ./gradlew test
        shell: bash

      - name: Execute gradle lint (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew lint